### ISSUE TITLE
Thoughts on update mode and check mode

### ISSUE THREAD

**Issue by teran-mckinney** [rhash/RHash#129]
Never seen `rhash` before, seems pretty nifty. I've used `mtree` from FreeBSD which is similar, more geared towards filesystem correctness than simple checksums.

Couple thoughts:

Might be nice to have a mode for using `-c hash-file` with recursive lists, to error if files are present which are not listed.

For update mode, if mtime and size were saved, `rhash` could behave like `rsync` and update files that had changes to mtime and/or size, rather than ignoring them.

I can elaborate more if you're curious, but also completely understand if you have no interest. I guess my idea on update would make the traditional update behavior more like a `-a/--append` by comparison.

Anyway, thanks for writing the tool. I'm evaluating it to see if I can use it in place of mtree for certain things.

**Comment by rhash** [comment]
> Might be nice to have a mode for using -c hash-file with recursive lists, to error if files are present which are not listed.

Nice idea

> For update mode, if mtime and size were saved, rhash could behave like rsync and update files that had changes to mtime and/or size, rather than ignoring them.

Currently 4 of the supported by RHash formats can store file size: SFV, torrent files, ed2k-links and magnet links, while only SFV stores mtime in its comments. I consider SFV format and ed2k-links obsolete and do not intend to develop their processing any further. Torrent files format is bad because of its info-hash, which depends on block-size extra parameters, so it's support is also frozen. Magnet links format without mtime parameter doesn't fit for rsync alternative.

So it should be some specific format, may be based on JSON. I don't know any existing good format fit for this purpose. Such rsync-like program should be written as a python script using librhash python bindings, since supporting new formats and rsync behavior is not a simple task, and python development is much faster than writing in C.
