### ISSUE TITLE
Use of relative path instead of absolute

### ISSUE THREAD

**Issue by i2324561w2** [rhash/RHash#137]
Is it possible to use a relative path? This way I could move a folder and not rehash everything again. I've seen I can write an output like this, but its check would fail.

Random things you can safely ignore: maybe someone else like me tried to use --check with "=", like its used on other options using files...maybe you could make it less ambiguous; I edited the output file deleting 1 char from the hash and it prints "can't parse line:" but in the end it still shows "Everything OK".

Thank you for this program!

**Comment by rhash** [comment]
> Is it possible to use a relative path?

yes

> I can write an output like this, but its check would fail.

can not reproduce

> use --check with "=", like its used on other options using files...maybe you could make it less ambiguous;

The difference is that the --check option changes program mode to 'Verification' and is applied to multiple hash-files, while options with "=" accept only a single argument.

> it prints "can't parse line:" but in the end it still shows "Everything OK".

The program works as expected. It reports error on the unparsed line and, at the end, prints verdict "Everything OK", meaning that all of the successfully parsed files with messages digests were verified.

One important point here is what in this case the program should print at the end. The line must be clearly understood by users, even in the case of large hash-files, where "can't parse line:" errors are scrolled away. If we add printing additional error "Parsing errors occurred: <COUNT_OF_ERRORS>" at the end, it will look excessive in the case of hash-file with a single unparsed line.

The other point is, such message will increase a bit codebase complexity and will add work for translators. Since the case of broken hash-files is very rare, I think the priority of this feature is very low.

**Comment by i2324561w2** [comment]
Then I'm doing it wrong to use a relative path. What I do:
rhash <folder> --verbose --speed --recursive --output=<output> --template=<template>
with template: \\%f %{mtime} %C \n
and check with:
rhash <folder> --verbose --speed --recursive --output=<output_check> --check <output>

**Comment by rhash** [comment]
The --check option doesn't support file formats with `%{mtime}` dates. Also you should use `%p` to print relative filepaths instead of `%f` filenames.

You can include dates and other information as comments with the following template content: `# %{mtime}\n%p %C\n`

**Comment by i2324561w2** [comment]
I tried using `# %{mtime}\n%p %C\n` and also `# %{mtime}\n%f %C\n` but they don't work if I move the folder with the files I've already hashed ("No such file or directory"). Also `%p` writes an absolute path.

**Comment by rhash** [comment]
If `%p` writes absolute path, while you specified a relative path on rhash command line, then it's a bug. Possibly It is the recently fixed #135 bug (with long paths on Windows).

When you specify --check option with --recursive, then RHash silently ignores all directories on the command line, so the following two command are equivalent:
~~~bash
rhash folder --verbose --speed --recursive --output=output_check --check output
rhash --verbose --speed --recursive --output=output_check --check output
~~~

After moving the _folder_, you need to run `rhash --check` from within the parent directory of the moved _folder_. Currently there is no other way to tell RHash that the _folder_ has been moved.

**Comment by i2324561w2** [comment]
Ok, now I understand it, thank you for your time, you can close this.

**Comment by Perkolator** [comment]
> > it prints "can't parse line:" but in the end it still shows "Everything OK".
> 
> The program works as expected. It reports error on the unparsed line and, at the end, prints verdict "Everything OK", meaning that all of the successfully parsed files with messages digests were verified.

And is it intended that rhash doesn't throw an error code on exit when this "can't parse line" happens? It would be nice to have at least that for detecting any errors with scripts (e.g. with `[[ "$?" == "0" ]]`).

**Comment by rhash** [comment]
@Perkolator, initially it was an intended behavior, but nowadays there are more hash-files generated by different programs and more hash functions, sometimes not understood by RHash.

You should open a separate issue to discuss this feature.
