### ISSUE TITLE
SHA-3: FIPS 202 draft has been published

### ISSUE THREAD

**Issue by sunaku** [rhash/RHash#15]
Please update the SHA-3 implementation in RHash to follow the [FIPS 202 **_publication_**](http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.202.pdf). :smiley_cat:

**Comment by rhash** [comment]
RHash since **v1.3.3** imlements SHA3 specified in the FIPS 202 draft (published on April 2014). This algorithm went **unchanged** to final FIPS 202 document.

To verify algorithm use the following tests:
$ echo -n '' | ./rhash --sha3-256 -
a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a  (stdin)
$ echo -n '' | ./rhash --sha3-512 -
a69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26  (stdin)

Compare to the test vectors on the wiki page [1] and NIST  test vectors [2].

Be careful! Many programs still implement old algorithm (sha3 prior to FIPS 202 draft). Many websites publish old test vectors. And some Linux distros (Ubuntu <=14.04, Debian  wheezy) provide old RHash versions with obsolete SHA3 implimentation ;)

[1] https://en.wikipedia.org/wiki/SHA-3
[2] http://csrc.nist.gov/groups/ST/toolkit/examples.html#aHashing
