### ISSUE TITLE
Update behavior changed

### ISSUE THREAD

**Issue by vj77a** [rhash/RHash#159]
I updated my linux distribution (mint) - it now has rhash v1.3.9 in the repo.  A script I previously had working is now broken.
With v.1.3.1 I could call
`rhash --md5 -u md5sum.txt`  which would work.  With v.1.3.9, rhash gives a syntax error.
As a workaround I can call
`rhash --md5 -u md5sum.txt *`.  Although that sort of works, I get an error message for every directory that only has an md5sum file `RHash: <dirname>: Is a directory`.
Is there a better way to call rhash than using a wildcard, that would suppress the 'Is a directory' messages?
As a side note, I would like to see which files the md5 is being updated.  Although verbose shows this, it also outputs 3 2 superflous lines every time viz.
`Config file: /etc/rhashrc`
`Format string is: %m  %p\n`
Is there any way to filter those out and just see which file's checksums have been changed or added?  (I've tried grep and tail but my bash skills aren't up to the task)
Thanks VERY much for a great tool.

**Comment by rhash** [comment]
The `--update` option has been changed due to request #33. The change was requested many times and the previous behavior has been often perceived as counterintuitive.

You should use:
~~~sh
rhash --md5 --maxdepth=1 -ru md5sum.txt .
~~~

Filter out two first lines and the last line with sed:
~~~sh
rhash --md5 --maxdepth=1 -vru md5sum.txt . 2>&1 | sed -e '1,2d; $d'
~~~

**Comment by vj77a** [comment]
Thanks you very much Alexsey.  Really, really appreciate that.

Worked like a charm!
