### ISSUE TITLE
hint for empty verification file and powershell redirect output command ">" 

### ISSUE THREAD

**Issue by andyjh92** [rhash/RHash#161]
Hi!

I'm using Windows 10 and RHash v1.4.1.

I do in powershell:
```
$ rhash  .\foo.txt > foo.sfv
$ cat foo.sfv
; Erzeugt von RHash v1.3.8 am 2021-05-15 um 18:43.13
; Geschrieben von Kravchenko Aleksey (Akademgorodok) - http://rhash.sf.net/
;
;           12  18:42.06 2021-05-15 foo.txt
foo.txt B26CB098
$ rhash.exe -c .\foo.sfv
--( Verifying foo.sfv )---------------------------------------------------------
--------------------------------------------------------------------------------
Everything OK
```

I thought "everything OK" means all files in foo.sfv are verified properly, but it means here that there is nothing to verify. Maybe you can add a hint that there is no file to verify and that redirecting output with ">" doesn't work on windows and that the user should use the "--output" option instead.

Thanks and regards, Andy

**Comment by rhash** [comment]
Hello.

Under Windows, the output redirection operator ">" correctly works in DOS shell `cmd.exe`, in FAR Manager and in MinGW shell.

The problem is caused by powershell, which operator ">" stores the program output in [UTF-16](https://en.wikipedia.org/wiki/UTF-16) (Little Endian) encoding.

RHash never has been programmed to accept files in UTF-16. Currently it silently skips all lines of such file.

**Details:** RHash uses C function `fgets()` to read a file line by line. This function can't correctly read strings containing `'\0'` character, like most UTF-16 strings. Encountering such file line was considered almost impossible, so the occurred error (about a line unterminated by `'\n'`) is not correctly reported, but the line is quietly skipped instead.

**Comment by rhash** [comment]
The suggestion "Maybe you can add a hint that there is no file to verify" is proposed in the issue #164:
> RHash should show some kind of warning for this case, as this makes it possible to trick the user into thinking everything is okay
