### ISSUE TITLE
BTIH is incorrect

### ISSUE THREAD

**Issue by JayBrown** [rhash/RHash#19]
rhash is a great tool, don't get me wrong, but the --btih output is not the correct infohash bencoded in the .torrent metadata. If users want the correct BT info hash, they should use e.g. the Transmission CLI, specifically the binary "transmission-show":

$ transmission-show /path/to/file.torrent | grep "Hash: " | awk '{print $2}'

**Comment by rhash** [comment]
The problem is that BTIH algorithm is not uniquely defined. It allows the implementation to choose any block size, which totally changes the hash value.

Some time ago RHash reflected uTorrent block size selection. But we cannot track other programs constantly.

BTIH value also depends on the name of the file being hashed. That is unthinkable for 'stable' hashes like MD5 and SHA1. Now I think it was a mistake from the start to support it :)

Conclusion: it's the BTIH algorithm specification that must be fixed.
