### ISSUE TITLE
Verify integrity from .torrent?

### ISSUE THREAD

**Issue by got2win** [rhash/RHash#30]
Hello!

If I have the files from a torrent. And I have the .torrent file. With RHash, is it able to read the .torrent file to verify all the files are good?

Thanks!

**Comment by rhash** [comment]
RHash can create a torrent file (with --torrent option), but not verify it.

The program can verify only Bittorent InfoHash (BTIH) and only uTorrent version of it. You can calculate it using --btih option.

Torrent support will not be developed in future, because InfoHash value is not uniquely defined - various torrent clients calculate different InfoHash for the same file.
