### ISSUE TITLE
install a symlink for librhash.so.0

### ISSUE THREAD

**Issue by misery** [rhash/RHash#42]
Please add a symlink librhash.so to librhash.so.0 on target "install".

Most linux distributions do not add a symlink for this. But cmake needs rhash since 3.8.0 which will be statically linked because it cannot find a "librhash.so" file.

**Comment by rhash** [comment]
I doesn't understand your request.

Neither librhash.so, nor librhash.so.0, nor librhash headers (required for cmake compilation) are installed by the "install" target.

Maybe discussed distribution incorrectly built the librhash -dev package?

**Comment by misery** [comment]
Yeah, sorry... I mean target "install-lib-shared"

**Comment by rhash** [comment]
The target install-lib-shared is used by Debian/Ubuntu to create librhash0 package, which, according to Debian policy, must not contain the librhash.so. symlink.

Since different Linux distribution use different policies, the LibRHash makefile contains simple targets to build a package from 'bricks'.

You should use command:
make install-lib-shared install-lib-static install-so-link

**Comment by misery** [comment]
Thanks... I missed install-so-link target
