### ISSUE TITLE
Feature Request: Store hash in extended attributes (similar to store hash in filename)

### ISSUE THREAD

**Issue by hjohn** [rhash/RHash#44]
Extended attributes seem to be an ideal location to store hashes.

A hash can be stored like:

    setfattr -n user.checksum.md5 -v "18c5342a060056b76ecea66bad47960c" test.txt

And retrieved with:

    getfattr -n user.checksum.md5 test.txt

To me it seems much cleaner than storing it in the filename, and especially for moved/copied files, it is easier to verify hashes again (the SFV files need to be edited when the path has changed).

**Comment by rhash** [comment]
While it looks like a good addition, I need to reject this FR.

First, not all filesystems support extended attributes, so the feature is not useful for everyone.

Second, this FR will require to introduce not only a single 'store-to-ext-attributes' option, but also 'ext-attributes-prefix'. Also, since storing to ext attributes is incompatible with --printf options, we need another option to set hash format (upper/lowercase and hex/base32), otherwise the program will store only in default hash format. This will complicate CLI and the manual.

Third, extended attributes are hidden information. It is usually lost by copy/download operations. Also one cannot check without special tools which files already have the hashes calculated.

Finally, you already can use RHash with extended attributes, using one of the following methods:
1. Generate and execute shell script using rhash --printf option.
2. Use the Librhash-python bindings to write your custom python script.

**Comment by hjohn** [comment]
Thanks for the tip on how to do this myself :)
