### ISSUE TITLE
Installing additional symlinks to rhash

### ISSUE THREAD

**Issue by eli-schwartz** [rhash/RHash#51]
Would it be possible to extend the SYMLINKS variable in the Makefile in order to allow install-symlinks to create a symlink for each hash method available?

**Comment by rhash** [comment]
Yes. 

From the man-page: 
> The default output format can also be changed by renaming the program or placing a hardlink/symlink to it with a name containing strings ‘crc32’, ‘md4’, ‘md5’, ‘sha1’, ‘sha256’ ‘sha512’, ‘tiger’, ‘tth’, ‘btih’, ‘aich’, ‘ed2k’, ‘ed2k-link’, ‘gost’, ‘gost-cryptopro’, ‘ripemd160’, ‘has160’, ‘whirlpool’, ‘edonr256’, ‘edonr512’, ‘snefru128’, ‘snefru256’, ‘sfv’ or ‘magnet’.

**Comment by eli-schwartz** [comment]
Thanks, but I was hoping you could add that to the Makefile in this repository...

**Comment by rhash** [comment]
Many Linux distributions already have commands:
md5sum, sha1sum, sha224sum, sha256sum, sha384sum, sha512sum, crc32
I don't want to duplicate them and disturb bash completion.

Most people also don't want old hash sums like aich and snefru. Btih is hardly a hash sum, because it depends on  not strictly specified block-size parameter.

Edonr is very fast and good hash (it's a sha3 candidate), but it is not well known and is rarely used. I think, I need some more reasons to add it.

As a packager you can pass SYMLINKS variable to the make command (or patch Makefile after unpacking tgz), and you'll get all symlinks you want.

**Comment by rhash** [comment]
done by commit cdaf43862229fb0f10d2b6b7448bcded2ef8edde

1. edonr256-hash edonr512-hash now are installed by default
2. you can change symlinks list by specifying configure --enable-symlinks=<LIST> option, e.g.:
./configure --enable-symlinks="crc32-hash sha256-hash ripemd160-hash"

See the man page for the possible symlink names: http://rhash.anz.ru/manpage.php#sect2

**Comment by rhash** [comment]
Included into RHash v1.3.6.
