### ISSUE TITLE
Build DEB packages

### ISSUE THREAD

**Issue by Skif-off** [rhash/RHash#62]
Почему в [control](https://salsa.debian.org/pkg-security-team/rhash/blob/debian/master/debian/control) в Build-Depends стоит ```debhelper (>= 11)```? Это значит, что в Ubuntu-based дистрибутивах до версии 18.04 собрать deb-пакеты без бубна не получится, хотя 16.04 LTS будет поддерживаться ещё несколько лет и 17.10 до июля (даже 1.3.5 недоступна), а релиз 18.04 будет только в апреле.

_Edit;_ Хм... в репе Debian в stretch-backports, для текущего релиза, вижу debhelper-11~bpo9+1, ещё от декабря 2017го (наверное, в Canonical или в сообществе руки не дошли или забили), хотя доступна только 1.3.3, а rhash-1.3.5 есть только в buster и sid... Похоже, чего-то не улавливаю в тонкостях циклов разработки?
Исправил на ```debhelper (>= 10)```, собрал, запустил тест с sha1 и sha512 - вроде порядок (Xubuntu 17.10).

**Comment by rhash** [comment]
Packages uploaded into Debian sid (unstable) are now recommended to use debhelper 11.
Uploaded packages are automatically moved to buster (testing) after a 10 days period, that's why buster has v1.3.5 . The v1.3.4 release have not met deadline to come into Debian stretch (stable), so it contains only v1.3.3.

I think you should setup PPA with RHash backport or push Ubuntu guys to make an official backport.
