### ISSUE TITLE
Windows - end of line is not take into with printf option

### ISSUE THREAD

**Issue by crile** [rhash/RHash#78]
Hi,

I generate `md5` file with this command

    rhash --md5 --output results.md5 --printf="%m %p\n" results.txt

But the `results.md5` still contains _carriage return_ at the end of lines.
I must use `dos2unix` to convert the _carriage return_ by _newline_.

Dos or unix type files are handle properly

    $ dos2unix.exe results.md5
    dos2unix: converting file results.md5 to Unix format...

    $ rhash --md5 --check results.md5

    --( Verifying results.md5 )-----------------------------------------------------
    results.txt                                      OK
    --------------------------------------------------------------------------------
    Everything OK

Even with the `--bsd` format, the line end with a _carriage return_.  

    rhash --md5 --output results.md5 --bsd results.txt

How can I modify the end of line format ?

Thanks

`rhash` version:

    $ rhash --version
    RHash v1.3.6

**Comment by rhash** [comment]
Couldn't reproduce it on Linux.
~~~sh
rhash --printf="\n" <any-file>
~~~
prints the same output as `printf "\n"`

**Comment by rhash** [comment]
The issue is reproduced under MSYS2 (Windows).
`$ ./rhash -p '\n' -m ''`
prints two characters. It is caused by Windows printf() function converting newline '\n' character to the standard Windows newline `CR+LF`.

This behavior was some years ago intentionally left unchanged for:
1. correct viewing of rhash-produced hash files with notepad,
2. to produce the same hash files as created by other Windows hashing software.

I hesitate that an option to control new-lines will be a popular one, so for now you should stick to using dos2unix.

**Comment by crile** [comment]
Sure, thank you for the answer
