### ISSUE TITLE
Reinforce SHA1 against collisions

### ISSUE THREAD

**Issue by sergeevabc** [rhash/RHash#87]
https://github.com/cr-marcstevens/sha1collisiondetection

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by rhash** [comment]
What do you mean under "Reinforce SHA1 against collisions"?

SHA1 is defined by [FIPS 180-4](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf) and its algorithm can't be changed.

**Comment by cr-marcstevens** [comment]
@rhash It is known how to compute collisions for SHA-1 and these already exist [https://shattered.io/](https://shattered.io/), MD5 is even ridiculous weak to collisions. To protect against collisions it is advised to use a secure hash function like SHA-2 or SHA-3.

Although MD5 is really considered insecure, SHA-1 can be strengthened using sha1collisiondetection:
> This library and command line tool were designed as near drop-in replacements for common SHA-1 libraries and sha1sum. They will compute the SHA-1 hash of any given file and additionally will detect cryptanalytic collision attacks against SHA-1 present in each file.

The library does not change the SHA-1 algorithm, but provides an additional warning flag whether an input file was created with a cryptanalytic collision attack. 
This can warn users of suspect files.
Additionally there is a special safe-hash mode that always returns the real SHA-1 hash when no collision attack was detected, yet returns a different safe hash when a collision attack was detected.

Note that the sha1collisiondetection library is currently the default SHA-1 implementation for git and GitHub, since git relies on SHA-1 to protect the integrity and authenticity of git repositories.

**Comment by rhash** [comment]
@cr-marcstevens, thank you for explanation.
I think this feature could be implemented to be turned on by a separate option.

But since I'm permanently overloaded by rl, the only chance to get it in is via a PR.

**Comment by rhash** [comment]
Although the feature looks useful, it is not planned due to my shortage of time.
Closing the issue.
