### ISSUE TITLE
Support for DSTU 7564:2014 and STB 34.101.31

### ISSUE THREAD

**Issue by MikhailKasimov** [rhash/RHash#90]
Hello!

Please, consider possibility of implementation for DSTU 7564:2014 and STB 34.101.31 hash-functions in RHash.

Thanks!

[1] Encryption Algorithm and Hash Function Implementations BELT (STB 34.101.31): https://github.com/luc-lynx/belt-algorithms
[2] Kupyna hash function (DSTU 7564:2014): https://github.com/sjinks/kupyna-c

**Comment by rhash** [comment]
Hi!

It would be a nice feature, but since RHash / LibRHash has a big list of features to implement, we, regrettably, need to reject this one, at least for now.

If you want more development to be done in RHash, you should help the project to find a sponsor or [become one](https://github.com/rhash/RHash/blob/master/docs/CONTRIBUTING.md), or [contribute it](https://github.com/rhash/RHash/blob/master/docs/CONTRIBUTING.md) in other ways ;)
